### PR TITLE
Update known-issue-446-oneLake-table-folder-not-removed.md

### PR DESCRIPTION
**Pull request by charithcaldera**
Requesting changes

### CODE REVIEW

**Comment by Jak-MS** [comment]
@mihart 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by SnehaGunda** [comment]
@mihart can you look into this PR?

**Comment by JasonWHowell** [comment]
This PR is in conflict because the file has been moved:
https://github.com/MicrosoftDocs/fabric-docs/blob/main/docs/get-started/known-issues/known-issue-446-onelake-table-folder-isnt-removed.md

**Comment by JasonWHowell** [comment]
#please-close

**Pull request closed without merging**
