### PR TITLE
Update buy-subscription.md

### PR DESCRIPTION
**Pull request by mihirwagleMSFT**
Availability of F SKUs updated.

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@KesemSharabi 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by mihart — APPROVED** [review]

**Comment by mihart** [comment]
#sign-off

**Review by mihart — APPROVED** [review]
Thanks Mihir

**Review by KesemSharabi — COMMENTED** [review]
Closing this PR. I removed the section and will add it back in on 1 June.

**Comment by KesemSharabi** [comment]
@ShannonLeavitt please close this PR.

**Pull request closed without merging**
