### PR TITLE
Update decision-guide-data-store.md

### PR DESCRIPTION
**Pull request by ArmandoLacerda**
Better describe the choice of data engine, not just storage, since storage is always OneLake.

This page in its original content implies that data can be stored in different places. As we know, data is preferably stored in delta parquet format. The Spark backed Lakehouse support expose folders and their unstructured or semi-structured files as the data engine (Spark) support these data file formats. 

It is evident to me that choosing either Lakehouse or Warehouse is a choice of data engine and their features. The same applies to Event House. In fact it is more evident when we consider Event House, when it reads in its documentation page (https://learn.microsoft.com/en-us/fabric/real-time-intelligence/eventhouse) "Event houses are the preferred **engine** for semi structured and free text analysis ."

As for Power BI Datamart, it is not a Fabric offering. Rather it is a Power BI feature. Granted it requires a premium subscription, which is equivalent to a Fabric capacity, but it is from before Fabric offering. It is not a special SQL edition like SQL MI and not even a special option in the copy activity or Dataflow Gen2. 

# Thank you for contributing to Microsoft Fabric documentation

## Fill out these items before submitting your pull request:

If you are working internally at Microsoft:
**Provide a link to an Azure DevOps Boards work item that tracks this feature/update.**

>
>

**Who is your primary Skilling team contact?** \@mention them individually tag them and let them review the PR before signing off.

>
>

## For internal Microsoft contributors, check off these quality control items as you go

- [ ] 1. **Check the Acrolinx report:** Make sure your Acrolinx Total score is **above 80 minimum** (higher is better) and with no spelling issues. Acrolinx ensures we are providing consistent terminology and using an appropriate voice and tone, and helps with localization.

- [ ] 2. **Successful build with no warnings or suggestions**: Review the build status to make sure **all files are green** (Succeeded).

- [ ] 3. **Preview the pages:**: Click each **Preview URL** link to view the rendered HTML pages on the review.learn.microsoft.com site to check the formatting and alignment of the page. Scan the page for overall formatting, and look at the parts you edited in detail.

- [ ] 4. **Check the Table of Contents:** If you are adding a new markdown file, make sure it is linked from the table of contents.

- [ ] 5. **#sign-off to request PR review and merge**: Once the pull request is finalized and ready to be merged, indicate so by typing `#sign-off` in a new comment in the Pull Request. If you need to cancel that sign-off, type `#hold-off` instead. *Signing off means the document can be published at any time.* Note, this is a formatting and standards review, not a technical review.

## Merge and publish
- After you `#sign-off`, there is a separate PR Review team that will review the PR and describe any necessary feedback before merging. 
- The review team will use the comments section in the PR to provide feedback if changes are needed. Address any blocking issues and sign off again to request another review.
- Once all feedback is resolved, you can `#sign-off` again. The PR Review team reviews and merges the pull request into the specified branch (usually the main branch or a release- branch).
- From the main branch, the change is merged into the live branch several times a day to publish it to the public learn.microsoft.com site.

### CODE REVIEW

**Comment by ArmandoLacerda** [comment]
@microsoft-github-policy-service agree

 

 

Armando Lacerda
 <https://linkedin.com/in/armando-lacerda> LInkedIn |  ***@***.***> ***@***.*** ­

**Comment by ArmandoLacerda** [comment]
@microsoft-github-policy-service agree

 

 

Armando Lacerda
 <https://linkedin.com/in/armando-lacerda> LInkedIn |  ***@***.***> ***@***.*** ­

**Comment by Court72** [comment]
@bradleyschacht

Can you review this PR? Sign off or approve if you accept the changes.

**Note**: To sign off, add a `#sign-off` comment to the PR.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by SnehaGunda** [comment]
@ArmandoLacerda Hope you are doing good!

I had a chat with @bradleyschacht and we don't think we can remove datamarts from the options described just yet. We have plans to make some changes to the decision guide, but we will keep datamarts in for the time being until we officially drop them. We didn't have an official date when that was going to be though. Since they are still preview, it may be possible for us to remove scenario #3 where the end decision is a datamart, but it should stay in the table and the list of resources linked at the bottom of the page.

**Comment by ArmandoLacerda** [comment]
Thanks for the update, Sneha. 

 

Please let me know if I can help with anything.

 

Armando Lacerda
 <https://linkedin.com/in/armando-lacerda> LInkedIn |  ***@***.***> ***@***.*** ­

**Comment by SnehaGunda** [comment]
Closing this PR WRT to the above conversation.

**Pull request closed without merging**
