### PR TITLE
Fixing the ARM template sample as it is not a valid template.

### PR DESCRIPTION
**Pull request by mrajess**
I removed the "id" property as this is not a valid property for this resource type. Additionally I parameterized the template for ease of use. Used template functions to reduce the number of properties that need to be set. And parameterized the SKU as it was hard coded to RA-GRS, which would change the replication configuration of someone's storage account if they weren't paying close attention.

# Thank you for contributing to Microsoft Fabric documentation

## Fill out these items before submitting your pull request:

If you are working internally at Microsoft:
**Provide a link to an Azure DevOps Boards work item that tracks this feature/update.**

>
>

**Who is your primary Skilling team contact?** \@mention them individually tag them and let them review the PR before signing off.

>
>

## For internal Microsoft contributors, check off these quality control items as you go

- [X] 1. **Check the Acrolinx report:** Make sure your Acrolinx Total score is **above 80 minimum** (higher is better) and with no spelling issues. Acrolinx ensures we are providing consistent terminology and using an appropriate voice and tone, and helps with localization.

- [X] 2. **Successful build with no warnings or suggestions**: Review the build status to make sure **all files are green** (Succeeded).

- [X] 3. **Preview the pages:**: Click each **Preview URL** link to view the rendered HTML pages on the review.learn.microsoft.com site to check the formatting and alignment of the page. Scan the page for overall formatting, and look at the parts you edited in detail.

- [X] 4. **Check the Table of Contents:** If you are adding a new markdown file, make sure it is linked from the table of contents.

- [X] 5. **#sign-off to request PR review and merge**: Once the pull request is finalized and ready to be merged, indicate so by typing `#sign-off` in a new comment in the Pull Request. If you need to cancel that sign-off, type `#hold-off` instead. *Signing off means the document can be published at any time.* Note, this is a formatting and standards review, not a technical review.

## Merge and publish
- After you `#sign-off`, there is a separate PR Review team that will review the PR and describe any necessary feedback before merging. 
- The review team will use the comments section in the PR to provide feedback if changes are needed. Address any blocking issues and sign off again to request another review.
- Once all feedback is resolved, you can `#sign-off` again. The PR Review team reviews and merges the pull request into the specified branch (usually the main branch or a release- branch).
- From the main branch, the change is merged into the live branch several times a day to publish it to the public learn.microsoft.com site.

### CODE REVIEW

**Comment by mrajess** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@paulinbar 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by paulinbar** [comment]
@meenalsri can you review this and sign off if you approve?

**Review by meenalsri — CHANGES_REQUESTED** [review]
Thanks for submitting this parameterized arm template. I found a few issues 
1. it fails validation if I provide just the workspace id.
2. if instead of workspace id, I provide the resource id then it works
3. every time I execute it, it replaces the resource ID with a new one.

**Comment by paulinbar** [comment]
Hi @mrajess and @meenalsri,
I am going to close this PR for now as I can't approve it for merging if there are still issues regarding it. Please feel free to reopen if there are further developments!

**Comment by paulinbar** [comment]
#please-close

**Pull request closed without merging**
