### PR TITLE
Update minimum gateway version to 3000.182.5

### PR DESCRIPTION
**Pull request by dazhang88**
Update minimum gateway version to 3000.182.5.

### CODE REVIEW

**Comment by miquelladeboer** [comment]
#sign-off

**Comment by ptyx507x** [comment]
#sign-off

**Comment by dazhang88** [comment]
#sign-off

**Review by ptyx507x — APPROVED** [review]

**Comment by ptyx507x** [comment]
#sign-off'

**Comment by ptyx507x** [comment]
#sign-off

**Review by nikkiwaghani — APPROVED** [review]

**Comment by Court72** [comment]
Thanks, @ptyx507x. 

Can you open a new PR in the private repo to correct your GitHub profile name in the `author` metadata field? Then PRMerger will let you sign off on PRs in the public repo.

**Comment by Court72** [comment]
Yes - thanks, @ptyx507x!

**Pull request merged**
